#! /usr/bin/env python
import sys

import gi

gi.require_version('Gtk', '3.0')
from gi.repository import Gtk as gtk


def main():
    color = gtk.Window().get_style().lookup_color(sys.argv[1])[1]
    print("#{:02x}{:02x}{:02x}".format(color.red // 256,
                                       color.green // 256,
                                       color.blue // 256))

if __name__ == "__main__":
    main()
