#! /usr/bin/env python3
import subprocess
import shlex

cmds = {
    "Logout": 'qshell -c "shutdown"',
    "Suspend": "systemctl suspend",
    "Hibernate": "systemctl hibernate",
    "Restart": "systemctl reboot",
    "Shutdown": "systemctl poweroff",
}

cmd = [
    "zenity",
    "--list",
    "--text=Choose an action:",
    "--column=foo",
    "--hide-header",
    f"--height={45 * len(cmds)}",
]

cmd.extend(cmds.keys())
choice = subprocess.run(cmd, capture_output=True).stdout.decode().strip()
subprocess.run(shlex.split(cmds[choice]))
